// Builds the `incidentaliq` schema, once, before the server accepts a request.
//
// Ported straight from schema.sql (D1/SQLite). Two real changes, not just dialect:
//   1. Everything is schema-qualified (`incidentaliq.captured_messages`, not `captured_messages`) —
//      same convention trip-monitoring uses for `mail.*`, so what a query touches is visible in the
//      query, never implied by search_path.
//   2. `trip_links` is now actually created. db.ts (getTripLinks/upsertTripLinks/applyTripLinks, the
//      plate↔container binding) has referenced this table since it was written, but it was never in
//      schema.sql — it only existed because someone created it on D1 by hand at some point. Whoever
//      runs this against a fresh database without that manual step gets a table-does-not-exist error
//      the first time a job sheet links a plate to a container.
//
// Every statement is idempotent (IF NOT EXISTS), so this runs on every boot and does nothing after
// the first.
//
// ⚠️ Does NOT create the `incidentaliq` schema itself, on purpose. `CREATE SCHEMA IF NOT EXISTS`
// still requires CREATE privilege on the DATABASE even when the schema already exists — Postgres
// checks the privilege before it checks existence, so the app's own low-privilege role gets a plain
// "permission denied for database" here, not a graceful no-op. Learned this the first time the
// converted server actually started up against tvl_dev. The schema has to be created once, by a
// superuser, owned by the app's role (AUTHORIZATION) — same one-time step already documented for
// `mail`. From then on the owning role has full rights INSIDE its own schema, no database-level
// CREATE grant needed, which is why the CREATE TABLE statements below are fine as this role.

const STATEMENTS: string[] = [
  // Raw messages uploaded by the phone. One row per captured message.
  `CREATE TABLE IF NOT EXISTS incidentaliq.captured_messages (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source          text NOT NULL,            -- 'viber' | 'messenger'
    group_name      text NOT NULL,
    sender          text,
    message         text,
    image_url       text,
    timestamp       text NOT NULL,            -- PH wall-clock ISO ("...+08:00")
    is_incidental   integer DEFAULT 0,
    trip_reference  text,                     -- container# | consignee | plate | booking ref
    reference_type  text,                     -- 'container_number' | 'consignee' | 'plate_number' | 'trip_id' | 'other'
    reference_source text,                    -- 'message' | 'history' | 'regex' | null
    raw_notif       integer DEFAULT 1,        -- 1 = from notification, 0 = from accessibility service
    content_hash    text,                     -- sha256(source|group|message) — durable dedup key
    store_only      integer DEFAULT 0,        -- 1 = archive-only group, never sent to Groq
    classified_at   text,                     -- null until the classifier has processed it
    synced_at       text                      -- when the backend received it
  )`,

  // One row per DETECTED incidental (a message can have several).
  `CREATE TABLE IF NOT EXISTS incidentaliq.incidentals (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id      integer NOT NULL REFERENCES incidentaliq.captured_messages(id),
    incidental_type text NOT NULL,
    status          text NOT NULL,            -- 'confirmed' | 'possible'
    confidence      double precision,
    amount          double precision,         -- usually NULL, amount doesn't matter for this use case
    trip_reference  text,                     -- denormalized for fast GROUP BY per trip
    UNIQUE (message_id, incidental_type, status)
  )`,

  // Cross-batch memory (Groq is stateless). One row per chat: the latest rolling summary.
  `CREATE TABLE IF NOT EXISTS incidentaliq.chat_state (
    group_name        text PRIMARY KEY,
    situation_summary text,
    updated_at         text
  )`,

  // Ops health: last cron outcome + lifetime metrics. One row per key, read via GET /health.
  `CREATE TABLE IF NOT EXISTS incidentaliq.system_status (
    key        text PRIMARY KEY,
    value      text,
    updated_at text
  )`,

  // Trip registry: durable per-chat list of known trip identifiers, so far-back trips stay linkable.
  `CREATE TABLE IF NOT EXISTS incidentaliq.trips (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name     text NOT NULL,
    trip_reference text NOT NULL,
    reference_type text,
    driver         text,
    helper         text,
    first_seen     text,
    last_seen      text,
    UNIQUE (group_name, trip_reference)
  )`,

  // Plate↔container binding — see the note above. A job sheet naming BOTH a plate and a container is
  // proof they're the same trip; this remembers that so an incidental reported under the plate
  // collapses under the container, the canonical id.
  `CREATE TABLE IF NOT EXISTS incidentaliq.trip_links (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name  text NOT NULL,
    alias       text NOT NULL,
    canonical   text NOT NULL,
    updated_at  text,
    UNIQUE (group_name, alias)
  )`,

  `CREATE INDEX IF NOT EXISTS idx_incidentals_trip ON incidentaliq.incidentals (trip_reference)`,
  `CREATE INDEX IF NOT EXISTS idx_msg_timestamp ON incidentaliq.captured_messages (timestamp)`,
  `CREATE INDEX IF NOT EXISTS idx_msg_unclassified ON incidentaliq.captured_messages (group_name, classified_at)`,
  `CREATE INDEX IF NOT EXISTS idx_msg_hash ON incidentaliq.captured_messages (content_hash)`,
];

export async function initSchema(run: (sql: string) => Promise<unknown>): Promise<void> {
  for (const statement of STATEMENTS) {
    await run(statement);
  }
}
